### ISSUE TITLE
Allow simulating hadrons

### ISSUE THREAD

**Issue by fschlueter** [icecube/event-generator#21]
Probably the simulation module should support simulating hadrons. One can run CMC before hand to convert hadrons into an electronmagnetic shower. However, if the energy drops below `1 TeV` the hadron is untouched by CMC (when using the `PropagateMuons` segment).

**Comment by fschlueter** [comment]
Or what do you thing @mhuen

**Comment by mhuen** [comment]
I think that could be a way to go about it. I'm not sure if there are performance issues related to that, since one hadronic cascade would be split up into many smaller ones, resulting in a larger number of required NN evaluations. The minimal thing one can do, would be to simply scale the energy of the hadron down to an EM-equivalent energy. This would disregard the shower profile change, but my guess is, that we are probably insensitive to that anyway. Alternatively, one could think about adding an option to pass in some sort of dictionary to the simulation that defines which particle types to simulate with which egenerator model. But also here, I am not sure how much it would improve things versus slow down the evaluation

**Comment by fschlueter** [comment]
This was solved with #18
